# Artifacts.toml
[[hdb_library]]
arch = "x86_64"
git-tree-sha1 = "21b8bf913c85aa8e10c6499d4cebdee9be13065a"
lazy = false
os = "windows"

    [[hdb_library.download]]
    sha256 = "a3db018d2849a577187dafe1571de9d418cf4d93d77e648239e9f29e845d8f4f"
    url = "https://github.com/linanisyugioh/HDB.jl/releases/download/v0.1.0/hdb_windows_x64.tar.gz"

[[hdb_library]]
arch = "x86_64"
git-tree-sha1 = "f065695bdb5892dea62d81239d7a1970977889da"
lazy = false
os = "linux"

    [[hdb_library.download]]
    sha256 = "31aa4b556c4c85ab6d6553f66958553d28e59107280b34b168894e8cc7cd24d6"
    url = "https://github.com/linanisyugioh/HDB.jl/releases/download/v0.1.0/hdb_linux_x64.tar.gz"