name = "HDB"
uuid = "0ab1eccf-93ac-46ef-a1d4-713a287ec040"
authors = ["linan linanisyugioh@163.com"]
version = "0.1.0"

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
