name = "HDB"
uuid = "0ab1eccf-93ac-46ef-a1d4-713a287ec040"
version = "0.1.0"
authors = ["linan linanisyugioh@163.com"]

[deps]
CBinding = "d43a6710-96b8-4a2d-833c-c424785e5374"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"

[compat]
CBinding = "1"
StringEncodings = "0.3"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
